#' Gene Set Enrichment Analysis (GSEA) from RNA-seq data
#'
#' @description
#' Performs Gene Set Enrichment Analysis (GSEA) using ranked gene lists
#' derived from differential expression results generated by \code{rna.compare()}.
#'
#' Gene ranking can be based on moderated t-statistics or log2 fold-change.
#' The function integrates MSigDB gene sets via \pkg{msigdbr} and performs enrichment
#' using \pkg{fgsea}, supporting multiple organisms and gene ID types.
#'
#' Annotation is performed automatically using
#' organism-specific \pkg{org.*.eg.db} databases.
#'
#' @param project \code{rna_project} object created by \code{rna.project()}.
#' @param group_col Character. Column name in \code{metadata} defining sample groups
#'   (default: \code{"Group"}). Used when computing rankings on-the-fly.
#' @param sample_col Character. Column name in \code{metadata} matching sample names
#'   (default: \code{"Sample"}).
#' @param contrast Character. Name of a comparison stored in the project.
#' If \code{NULL}, the last comparison is used.
#' @param top_n Integer. Number of top enriched pathways to retain (default: \code{10}).
#' @param geneset_collection Character. MSigDB collection (e.g., \code{"C2"}, \code{"C5"}).
#' @param geneset_subcollection Character. Subcollection within MSigDB
#'   (e.g., \code{"GO:BP"}, \code{"CP:REACTOME"}).
#' @param ranking_method Character. Method used for gene ranking:
#'   \code{"stat"} (t-statistic) or \code{"log2fc"}.
#' @param padj_gsea Numeric. Adjusted p-value cutoff for filtering enriched pathways
#'   (default: \code{0.05}).
#' @param heatmap_mode Character. Strategy for selecting pathways in the heatmap:
#'   \code{"adaptive"} (balanced), but keeping biological effect
#'   \code{"NES_ordered"} (order by NES) or \code{"split_direction"} (balanced up/down).
#' @param plot_heatmap Logical. Whether to display a NES heatmap of enriched pathways.
#' @param enrich_plot Logical. Whether to generate enrichment plots for top pathways.
#' @param seed Optional integer used to set the random seed for reproducibility.
#' If `NULL`, the existing random number generator state is used.
#' @param save Logical. Whether to store results in the active \code{rna_project}.
#'
#' @section Common gene set configurations:
#'
#' The MSigDB database is organized into collections (e.g., "C2", "C5"),
#' which may not be intuitive. Below are biologically meaningful configurations
#' for common analysis goals:
#'
#' \strong{General biology (Hallmark pathways)}
#' \itemize{
#'   \item Concise, non-redundant representation of major biological processes
#'   \item Recommended as a starting point
#'   \item \code{geneset_collection = "H"}
#' }
#'
#' \strong{Classical pathways (Reactome, KEGG, BioCarta)}
#' \itemize{
#'   \item Detailed signaling and metabolic pathways
#'   \item More granular but also more redundant
#'   \item \code{geneset_collection = "C2"}
#'   \item \code{geneset_subcollection = "CP"}
#' }
#'
#' \strong{Reactome pathways (highly curated)}
#' \itemize{
#'   \item Structured, hierarchical pathway knowledgebase
#'   \item Good balance between detail and interpretability
#'   \item \code{geneset_collection = "C2"}
#'   \item \code{geneset_subcollection = "CP:REACTOME"}
#' }
#'
#' \strong{Gene Ontology (GO)}
#' \itemize{
#'   \item Broad functional annotation (can be redundant)
#'   \item \code{geneset_collection = "C5"}
#'   \item Subcollections:
#'     \itemize{
#'       \item \code{"GO:BP"} – biological processes
#'       \item \code{"GO:MF"} – molecular functions
#'       \item \code{"GO:CC"} – cellular components
#'     }
#' }
#'
#' \strong{Cell type signatures}
#' \itemize{
#'   \item Gene sets representing specific cell populations
#'   \item Useful for inferring cellular composition or activation
#'   \item \code{geneset_collection = "C8"}
#' }
#'
#' \strong{Immunologic signatures (C7)}
#' \itemize{
#'   \item Immunologic gene sets (stimuli, cell states, perturbations)
#'   \item Particularly useful in infection, vaccination, and inflammation studies
#'   \item \code{geneset_collection = "C7"}
#' }
#'
#' \strong{Oncogenic signatures}
#' \itemize{
#'   \item Gene sets derived from oncogenic pathway perturbations
#'   \item Useful for cancer-related analyses
#'   \item \code{geneset_collection = "C6"}
#' }
#'
#' \strong{Tip: Choosing a collection:}
#' \itemize{
#'   \item Use Hallmark ("H") for a clean global signal
#'   \item Use C2/Reactome for pathway-level interpretation
#'   \item Use GO (C5) for hypothesis generation
#'   \item Use C7/C8 when biological context (immune/cell types) is central
#' }
#'
#' \strong{Interpretation:}
#' Positive normalized enrichment scores (NES) indicate pathways enriched
#' in the test condition, while negative NES values indicate enrichment
#' in the reference condition.
#'
#' @details
#' This function operates on results generated by \code{rna.compare()},
#' ensuring consistency between differential expression and enrichment analysis.
#'
#' The selected comparison defines the gene ranking used in GSEA.
#'
#' For zebrafish, GO collections (C5) are not available in MSigDB and are
#' automatically replaced with Reactome pathways (C2:CP:REACTOME).
#'
#' @return
#' An object of class \code{gsea_result} containing:
#' \describe{
#'   \item{ranking}{Named numeric vector of ranked genes.}
#'   \item{pathways}{List of gene sets used in the analysis.}
#'   \item{gsea_full}{Full GSEA result table.}
#'   \item{gsea_top}{Filtered table of top enriched pathways.}
#'   \item{enrich_plots}{List of enrichment plots (if requested).}
#'   \item{contrast}{Comparison used for ranking.}
#'   \item{params}{List of analysis parameters.}
#' }
#'
#' @section Gene ranking:
#' \itemize{
#'   \item \code{stat}: prioritizes genes with strong effect size and low variance.
#'   \item \code{log2fc}: emphasizes magnitude of change.
#' }
#'
#' @section Visualization:
#' \itemize{
#'   \item Enrichment plots show running enrichment score for individual pathways.
#'   \item Heatmaps summarize normalized enrichment scores (NES).
#' }
#'
#' @section Pipeline context:
#' This function is typically used after \code{rna.normalize()} and before
#' downstream analyses such as \code{rna.compare()}, or clustering.
#'
#' @seealso
#' \code{\link[fgsea]{fgseaMultilevel}},
#' \code{\link[msigdbr]{msigdbr}},
#' \code{\link{rna.compare}}
#'
#' @examples
#' \dontrun{
#' # Using last comparison
#' rna.gsea(project = my_project)
#'
#' # Using a specific comparison
#' rna.gsea(my_project,
#'          contrast = "treated_vs_control")
#' }
#'
#' @export

rna.gsea <- function(project,
                     group_col = "Group",
                     sample_col = "Sample",
                     contrast = NULL,
                     top_n = 10,
                     geneset_collection = "C5",
                     geneset_subcollection = "GO:BP",
                     ranking_method = c("stat", "log2fc"),
                     padj_gsea = 0.05,
                     heatmap_mode = c("adaptive", "NES_ordered", "split_direction"),
                     plot_heatmap = TRUE,
                     enrich_plot = FALSE,
                     seed = NULL,
                     save = TRUE
) {

  # ===========================================================================
  # 0) Basic checks
  # ===========================================================================
  heatmap_mode <- match.arg(heatmap_mode)
  ranking_method = match.arg(ranking_method)

  geneset_collection <- toupper(geneset_collection)

  pkgs <- c("msigdbr",
            "stringr"
  )

  bioc_pkgs <- c("BiocParallel",
                 "fgsea",
                 "AnnotationDbi")

  .check_dependencies(pkgs)
  .check_dependencies(pkgs, bioc = TRUE)

  # Check ggplot2
  if (enrich_plot && !requireNamespace("ggplot2", quietly = TRUE)) {
    .check_dependencies("ggplot2")
  }

  # Check heatmap
  if (plot_heatmap) {
    .check_dependencies("pheatmap")
  }

  # --- Set seed ---
  old_seed <- .set_seed(seed)
  on.exit(.reset_seed(old_seed), add = TRUE)

  # ===========================================================================
  # 1) Get active project
  # ===========================================================================
  proj <- project

  expr <- as.matrix(.get_expr(proj))
  metadata <- .get_meta(proj)

  organism <- .get_organism(proj)
  message("[rna.gsea] Using organism from project:", organism)

  comps <- .get_comp(proj)
  gene_map <- .get_gene_annotation(proj)

  # ===========================================================================
  # 3) Validate input
  # ===========================================================================
  # --- Organism ---
  orgdb <- switch(
    organism,
    mouse     = org.Mm.eg.db::org.Mm.eg.db,
    human     = org.Hs.eg.db::org.Hs.eg.db,
    zebrafish = org.Dr.eg.db::org.Dr.eg.db,
    stop("`organism` must be 'human', 'mouse' or 'zebrafish'.")
  )

  # --- Case 1: use last comparison automatically
  contrast_id <- .get_last_or_selected(
    comps,
    contrast,
    what = "comparison"
  )

  comp_obj <- .get_comp_obj(proj, contrast_id)

  res_df <- comp_obj$res

  contrast <- c(
    comp_obj$groups$reference,
    comp_obj$groups$test
  )

  message("[rna.gsea] Using comparison: ", contrast[2], " vs ", contrast[1])

  collections_without_sub <- c("H","C1","C6","C7","C8")

  if (geneset_collection %in% collections_without_sub &&
      !is.null(geneset_subcollection)) {

    message(
      "[rna.gsea] Collection ", geneset_collection,
      " does not support subcollections. Ignoring 'geneset_subcollection'."
    )

    geneset_subcollection <- NULL
  }

  # ===========================================================================
  # 4) Ranking computation
  # ===========================================================================

  if (!is.null(res_df)) {

    # ---- From stored comparison ----
    if (ranking_method == "stat") {

      if (!"stat" %in% colnames(res_df))
        stop("Stored comparison does not contain 'stat' column.")

      gene_ranking <- res_df$stat

    } else {

      if (!"log2FoldChange" %in% colnames(res_df))
        stop("Stored comparison does not contain 'log2FoldChange' column.")

      gene_ranking <- res_df$log2FoldChange
    }

    names(gene_ranking) <- rownames(res_df)

  } else {

    # ---- Contrast based ranking ----
    if (is.null(contrast) || length(contrast) != 2) {
      stop("Provide a valid contrast (vector of length 2) or specify using 'contrast'.")
    }

    # --- Prepare normalized data and metadata ---
    grp <- metadata[[group_col]]

    g1 <- contrast[1]
    g2 <- contrast[2]

    if (!all(c(g1, g2) %in% unique(grp))) {
      stop("One or both contrast groups not found in metadata.")
    }

    expr1 <- expr[, grp == g1, drop = FALSE]
    expr2 <- expr[, grp == g2, drop = FALSE]

    if (ncol(expr1) < 1 || ncol(expr2) < 1) {
      stop("One of the contrast groups has no samples.")
    }

    if (ranking_method == "stat") {

      m1 <- rowMeans(expr1)
      m2 <- rowMeans(expr2)

      v1 <- apply(expr1, 1, var)
      v2 <- apply(expr2, 1, var)

      n1 <- ncol(expr1)
      n2 <- ncol(expr2)

      se <- sqrt(v1/n1 + v2/n2)

      gene_ranking <- (m2 - m1) / se
      gene_ranking[!is.finite(gene_ranking)] <- 0

    } else {

      mean1 <- rowMeans(expr1)
      mean2 <- rowMeans(expr2)

      gene_ranking <- log2((mean2 + 1) / (mean1 + 1))
    }

    names(gene_ranking) <- rownames(expr)
  }

  # ---- Cleaning and ordering ----
  gene_ranking <- gene_ranking[is.finite(gene_ranking)]
  gene_ranking <- sort(gene_ranking, decreasing = TRUE)

  # ===========================================================================
  # 5) Load global gene sets
  # ===========================================================================

  # ---- Compatibility check for zebrafish ----
  if (organism == "zebrafish" && geneset_collection == "C5") {

    warning(
      "GO collections (C5) not available for zebrafish in MSigDB. ",
      "Switching to C2:REACTOME."
    )

    geneset_collection   <- "C2"
    geneset_subcollection <- "CP:REACTOME"
  }

  if (geneset_collection %in% c("H", "C1", "C6", "C7", "C8")) {

    msig <- msigdbr::msigdbr(
      species = switch(
        organism,
        mouse = "Mus musculus",
        human = "Homo sapiens",
        zebrafish = "Danio rerio"
      ),
      collection = geneset_collection
    )

  } else {

    msig <- msigdbr::msigdbr(
      species = switch(
        organism,
        mouse = "Mus musculus",
        human = "Homo sapiens",
        zebrafish = "Danio rerio"
      ),
      collection = geneset_collection,
      subcollection = geneset_subcollection
    )
  }

  pathways <- split(msig$gene_symbol, msig$gs_name)

  # Clean pathway names for plotting
  clean_names <- .smart_pathway_name(names(pathways))
  names(pathways) <- clean_names

  # ===========================================================================
  # 5.5) ID conversion
  # ===========================================================================
  gene_ids <- names(gene_ranking)

  gene_symbols <- gene_map$symbol[
    match(gene_ids, gene_map$gene_id)
  ]

  # Smart fallback
  gene_symbols[is.na(gene_symbols) | gene_symbols == ""] <- gene_ids[
    is.na(gene_symbols) | gene_symbols == ""
  ]

  # Ensure valid names
  valid <- !is.na(gene_symbols) & gene_symbols != ""

  gene_ranking <- gene_ranking[valid]
  names(gene_ranking) <- gene_symbols[valid]

  # Remove duplicated
  gene_ranking <- tapply(gene_ranking, names(gene_ranking), mean)
  gene_ranking <- sort(gene_ranking, decreasing = TRUE)

  if (is.null(names(gene_ranking))) {
    stop("gene_ranking lost its names after aggregation.")
  }

  # ===========================================================================
  # 6) GSEA
  # ===========================================================================
  tapply(gene_ranking, names(gene_ranking), median)

  gsea_res <- fgsea::fgseaMultilevel(
    pathways = pathways,
    stats    = gene_ranking,
    minSize  = 10,
    maxSize  = 500,
    BPPARAM  = BiocParallel::SerialParam()
  )

  gsea_res <- gsea_res[order(gsea_res$padj), ]
  gsea_sig <- gsea_res[gsea_res$padj < padj_gsea, ]
  gsea_top <- utils::head(gsea_sig, top_n)

  gsea_res$pathway <- .smart_pathway_name(gsea_res$pathway)
  gsea_res$pathway <- make.unique(gsea_res$pathway)
  names(pathways)  <- .smart_pathway_name(names(pathways))

  if (nrow(gsea_res) == 0) {
    warning(
      "GSEA returned no enriched pathways. ",
      "Check gene ID compatibility between ranking and pathways."
    )
  }

  # ===========================================================================
  # 7) Enrichment plots
  # ===========================================================================
  enrich_plots <- NULL

  if (enrich_plot && nrow(gsea_top) > 0) {

    enrich_plots <- lapply(seq_len(nrow(gsea_top)), function(i) {

      fgsea::plotEnrichment(
        pathways[[gsea_top$pathway[i]]],
        gene_ranking
      ) +
        ggplot2::labs(
          title = gsea_top$pathway[i],
          subtitle = paste0(
            "NES = ", round(gsea_top$NES[i], 2),
            " | padj = ", signif(gsea_top$padj[i], 3)
          )
        ) +
        ggplot2::theme_classic(base_size = 12)
    })

    names(enrich_plots) <- gsea_top$pathway
  }

  if (interactive()) {
    lapply(enrich_plots, print)
  }

  # ===========================================================================
  # 8) Prepare pathways for NES heatmap
  # ===========================================================================
  if (plot_heatmap && nrow(gsea_sig) > 0) {

    gsea_heat <- NULL
    heatmap_title <- "GSEA heatmap"

    if (heatmap_mode == "adaptive") {

      gsea_pos <- gsea_sig[gsea_sig$NES > 0, ]
      gsea_neg <- gsea_sig[gsea_sig$NES < 0, ]

      gsea_pos <- gsea_pos[order(-gsea_pos$NES), ]
      gsea_neg <- gsea_neg[order(gsea_neg$NES), ]

      n_pos <- nrow(gsea_pos)
      n_neg <- nrow(gsea_neg)

      if ((n_pos + n_neg) > 0) {

        prop_pos <- n_pos / (n_pos + n_neg)

        n_pos_top <- round(top_n * prop_pos)
        n_neg_top <- top_n - n_pos_top

        if (n_pos > 0 && n_pos_top == 0) n_pos_top <- 1
        if (n_neg > 0 && n_neg_top == 0) n_neg_top <- 1

        gsea_heat <- rbind(
          utils::head(gsea_pos, n_pos_top),
          utils::head(gsea_neg, n_neg_top)
        )
      }

      heatmap_title <- "GSEA - adaptive NES"

    } else if (heatmap_mode == "NES_ordered") {

      gsea_heat <- gsea_sig[
        order(gsea_sig$NES, decreasing = TRUE),
      ]
      gsea_heat <- utils::head(gsea_sig, top_n)

      heatmap_title <- paste0(
        "GSEA - NES ordered\n"
      )

    } else if (heatmap_mode == "split_direction") {

      n_each <- floor(top_n / 2)

      gsea_pos <- gsea_sig[gsea_sig$NES > 0, ]
      gsea_neg <- gsea_sig[gsea_sig$NES < 0, ]

      gsea_pos <- gsea_pos[order(-gsea_pos$NES), ]
      gsea_neg <- gsea_neg[order(gsea_neg$NES), ]

      gsea_heat <- rbind(
        utils::head(gsea_pos, n_each),
        utils::head(gsea_neg, n_each)
      )

      heatmap_title <- paste0(
        "GSEA - split direction NES\n"
      )
    }

    if (nrow(gsea_heat) > 0) {

      rown <- make.unique(gsea_heat$pathway)

      heat_df <- data.frame(
        row.names = rown,
        neg = ifelse(gsea_heat$NES < 0, -gsea_heat$NES, 0),
        pos = ifelse(gsea_heat$NES > 0,  gsea_heat$NES, 0)
      )

      colnames(heat_df) <- contrast

      # Plot heatmap
      pheatmap::pheatmap(
        heat_df,
        cluster_rows = TRUE,
        cluster_cols = FALSE,
        angle_col = 45,
        color = grDevices::colorRampPalette(
          c("#4C72B0", "#DDDDDD", "#C44E52")
        )(100),
        border_color = "white",
        labels_row = stringr::str_wrap(rownames(heat_df), width = 40),
        main = heatmap_title
      )
    }
  }

  # ===========================================================================
  # 9) RNG handling
  # ===========================================================================
  rng_state <- if (exists(".Random.seed", envir = .GlobalEnv)) .Random.seed else NULL

  seed <- if (is.null(seed)) {
    "not set"
  } else {
    as.character(seed)
  }

  # ===========================================================================
  # 10) Output
  # ===========================================================================
  direction_summary <- list(
    up = sum(gsea_top$NES > 0),
    down = sum(gsea_top$NES < 0),
    total = nrow(gsea_top),
    proportion_up = mean(gsea_top$NES > 0),
    proportion_down = mean(gsea_top$NES < 0)
  )

  params <- list(
    timestamp = Sys.time(),
    organism = organism,
    group_col = group_col,
    sample_col = sample_col,
    contrast = contrast,
    ranking_method = ranking_method,
    geneset_collection = geneset_collection,
    geneset_subcollection = geneset_subcollection,
    padj_gsea = padj_gsea,
    top_n = top_n,
    heatmap_mode = heatmap_mode,
    gene_id_type = proj$input$imp_data$gene_id_type,
    seed = seed,
    rng_state = rng_state
  )

  obj <- list(
    params = params,
    ranking = gene_ranking,
    pathways = pathways,
    gsea_full = gsea_res,
    gsea_top = gsea_top,
    direction_summary = direction_summary,
    input_summary = list(
      n_genes = length(gene_ranking),
      gene_id_type = params$gene_id_type
    ),
    enrich_plots = enrich_plots
  )

  class(obj) <- "gsea_result"

  # ===========================================================================
  # 11) Attach to project
  # ===========================================================================
  if (save) {

    proj <- .attach_to_project(
      proj,
      obj,
      slot = "analyses",
      subtype = "gsea",
      prefix = "gsea",
      log = list(
        contrast = paste(contrast, collapse = " vs "),
        ranking = ranking_method,
        genesets = paste0(geneset_collection, ":", geneset_subcollection),
        n_sig = sum(gsea_res$padj < padj_gsea),
        top_pathway = ifelse(nrow(gsea_top) > 0, gsea_top$pathway[1], NA),
        seed = seed
      )
    )

  }

  print(obj)
  return(invisible(proj))

}

# ===========================================================================
# 12) Print S3
# ===========================================================================
#' Print method for gsea_result objects
#'
#' Displays a formatted summary of a \code{gsea_result} object,
#' including contrast, organism, and top enriched pathways.
#'
#' gsea_result object
#'
#' An object returned by \code{rna.gsea()} containing
#' GSEA results, rankings, and plots.
#'
#' @section Slots:
#' \describe{
#'   \item{ranking}{Named vector}
#'   \item{gsea_full}{Full table}
#'   \item{gsea_top}{Filtered table}
#'   ...
#' }
#'
#' @name gsea_result
#' @docType class
NULL
#'
#' @param x An object of class \code{gsea_result}.
#' @param ... Further arguments (ignored).
#' @return Invisibly returns \code{x}.
#' @method print gsea_result
#' @export
#' @rdname gsea_result

print.gsea_result <- function(x, ...) {

  .print_header("GSEA Result")

  .print_block("Overview", function() {
    cat("Class: gsea_result\n")
    cat("Contrast: ", paste(x$params$contrast, collapse = " vs "), "\n")
    cat("Significant pathways: ",
        sum(x$gsea_full$padj < x$params$padj_gsea),
        "\n", sep = "")
    cat("Seed: ", x$params$seed, "\n", sep = "")
  })

  .print_block("Direction summary", function() {
    cat("Upregulated pathways: ", x$direction_summary$up, "\n")
    cat("Downregulated pathways: ", x$direction_summary$down, "\n")
    cat("Up proportion: ", round(x$direction_summary$proportion_up, 2), "\n")
  })

  .print_block("Top enriched pathways", function(){
    print(utils::head(x$gsea_top$pathway, 5))
  })

  invisible(x)
}

# ===========================================================================
# 13) Summary method
# ===========================================================================
#' Summary method for gsea_result objects
#'
#' Returns a table of top enriched pathways from a
#' \code{gsea_result} object.
#' @param object An object of class \code{gsea_result}.
#' @param ... Further arguments (ignored).
#' @return A data.frame containing the top GSEA results.
#' @export
#' @rdname gsea_result

summary.gsea_result <- function(object, ...) {
  object$gsea_top
}
