#' Expression heatmap of normalized RNA-seq data
#'
#' Generates a clustered heatmap from normalized expression data, allowing
#' flexible gene selection based on differential expression results,
#' variance, or user-defined gene sets.
#'
#' @param project \code{rna_project} object created by \code{rna.project()}.
#' @param contrast Character or numeric. Identifier of a stored comparison
#'   generated by \code{rna.compare()}. When provided, genes are selected based
#'   on differential expression statistics from this comparison.
#' @param group_col Character. Column name in metadata defining sample groups
#'   for column annotation (default: \code{"Group"}).
#' @param top_n Integer. Number of genes to include when using
#'   \code{contrast} or \code{use_variance} (default: \code{100}).
#' @param genes Character vector. User-defined gene identifiers to include in
#'   the heatmap. Overrides other selection methods if provided.
#' @param use_variance Logical. If \code{TRUE}, selects the top \code{top_n}
#'   most variable genes across samples (default: \code{FALSE}).
#' @param zscore Logical. If \code{TRUE}, applies row-wise z-score normalization
#'   prior to plotting (default: \code{TRUE}).
#' @param cluster_rows Logical. Whether to cluster genes (rows)
#'   (default: \code{TRUE}).
#' @param cluster_cols Logical. Whether to cluster samples (columns)
#'   (default: \code{TRUE}).
#' @param show_rownames Logical. Whether to display gene names
#'   (default: \code{FALSE}).
#' @param show_colnames Logical. Whether to display sample names
#'   (default: \code{FALSE}).
#' @param show_regulation Logical. If \code{TRUE}, adds a row annotation
#'   indicating up- and down-regulated genes when using
#'   \code{contrast} (default: \code{FALSE}).
#' @param seed Optional integer used to set the random seed for reproducibility.
#' If `NULL`, the existing random number generator state is used.
#' @param save Logical. Whether to store results in the active
#'   \code{rna_project} (default: \code{TRUE}).
#'
#' @return Invisibly returns an object of class \code{heatmap_result} containing:
#' \describe{
#'   \item{genes_used}{Character vector of genes included in the heatmap.}
#'   \item{heatmap_matrix}{Matrix used for plotting (z-scored if applicable).}
#'   \item{annotation_col}{Data frame with sample group annotations.}
#'   \item{contrast}{Comparison used (if applicable).}
#'   \item{params}{List of parameters and metadata.}
#' }
#'
#' @details
#' Gene selection follows a mutually exclusive strategy:
#' \itemize{
#'   \item \code{contrast}: selects genes based on differential expression
#'   statistics (typically lowest \code{padj} or \code{pvalue}).
#'   \item \code{use_variance}: selects genes with highest variance across samples.
#'   \item \code{genes}: uses a user-defined gene set.
#' }
#'
#' If no selection method is provided, the function defaults to using the most
#' recent stored comparison.
#'
#' Expression values can be optionally standardized (z-score) per gene to
#' highlight relative expression patterns across samples. Values are clipped
#' to the range \code{[-2, 2]} to improve visualization stability.
#'
#' The heatmap is generated using \pkg{pheatmap}, with optional row and column
#' clustering and annotation tracks.
#'
#' @examples
#' \dontrun{
#' # Basic usage
#' rna.heatmap(project = my_project)
#'
#' # Using DEGs from a stored comparison
#' rna.heatmap(my_project,
#'             contrast = "Control_vs_Treated")
#'
#' # Using most variable genes
#' rna.heatmap(my_project,
#'             use_variance = TRUE)
#'
#' # Using a custom gene set
#' rna.heatmap(my_project,
#'             genes = c("GeneA", "GeneB", "GeneC"))
#' }
#'
#' @importFrom utils tail
#'
#' @export

rna.heatmap <- function(project,
                        contrast = NULL,
                        group_col = "Group",
                        top_n = 100,
                        genes = NULL,
                        use_variance = FALSE,
                        zscore = TRUE,
                        cluster_rows = TRUE,
                        cluster_cols = TRUE,
                        show_rownames = FALSE,
                        show_colnames = FALSE,
                        show_regulation = FALSE,
                        seed = NULL,
                        save = TRUE
                        ) {

  res_df <- NULL

  # ---------------------------
  # 0) Basic checks
  # ---------------------------
  .check_dependencies("pheatmap")

  # --- Set seed ---
  old_seed <- .set_seed(seed)
  on.exit(.reset_seed(old_seed), add = TRUE)

  # ---------------------------
  # 1) Get active project
  # ---------------------------
  proj <- project

  expr_mat <- as.matrix(.get_expr(proj))
  metadata <- .get_meta(proj)
  comps <- .get_comp(proj)

  gene_id_type <- .get_gene_id_type(proj)
  organism <- .get_organism(proj)

  # ---------------------------
  # 2) Validate input
  # ---------------------------
  OrgDb <- switch(
    organism,
    human = org.Hs.eg.db::org.Hs.eg.db,
    mouse = org.Mm.eg.db::org.Mm.eg.db,
    zebrafish = org.Dr.eg.db::org.Dr.eg.db
  )

  if (!"Sample" %in% colnames(metadata))
    stop("Metadata must contain a 'Sample' column.")

  # ---------------------------
  # 3) Resolve comparison
  # ---------------------------
  if (is.null(genes) && !use_variance) {

    contrast_id <- .get_last_or_selected(
      comps,
      contrast,
      what = "comparison"
    )

    comp_obj <- .get_comp_obj(proj, contrast_id)

    res_df <- comp_obj$res

    message(
      "[rna.heatmap] Using comparison: ",
      comp_obj$groups$test, " vs ", comp_obj$groups$reference
    )

  } else {

    res_df <- NULL
  }

  # ---------------------------
  # 4) Mode validation
  # ---------------------------
  if (sum(c(!is.null(contrast), !is.null(genes), use_variance)) > 1) {
    stop("Choose only one: contrast, genes, or use_variance.")
  }

  # ---------------------------
  # 5) Gene selection
  # ---------------------------
  genes_sel <- .select_heatmap_genes(
    expr_mat = expr_mat,
    res_df = res_df,
    genes = genes,
    use_variance = use_variance,
    top_n = top_n
  )

  gene_regulation <- NULL

  if (!is.null(res_df)) {

    common_genes <- intersect(genes_sel, rownames(res_df))

    gene_regulation <- data.frame(
      Regulation = ifelse(
        res_df[common_genes, "log2FoldChange"] > 0,
        "Up",
        "Down"
      ),
      row.names = common_genes
    )
  }

  ann_colors <- list(
    Regulation = c(
      Up = "#E69F00",
      Down = "#009E73"
    )
  )

  genes_sel <- intersect(genes_sel, rownames(expr_mat))
  mat_top <- expr_mat[genes_sel, , drop = FALSE]

  if (length(genes_sel) < 2) {
    stop(
      "Heatmap requires at least 2 genes.\n",
      "Selected genes: ", length(genes_sel)
    )
  }

  # ---------------------------
  # 6) Map gene IDs to SYMBOL
  # ---------------------------
  from_type <- toupper(gene_id_type)

  gene_symbols <- tryCatch({
    AnnotationDbi::mapIds(
      OrgDb,
      keys = genes_sel,
      keytype = from_type,
      column = "SYMBOL",
      multiVals = "first"
    )
  }, error = function(e) {
    warning("Gene ID mapping failed. Using original IDs.")
    NULL
  })

  if (!is.null(gene_symbols)) {

    new_names <- gene_symbols[genes_sel]

    # fallback
    new_names[is.na(new_names)] <- genes_sel[is.na(new_names)]

    new_names <- make.unique(new_names)
    rownames(mat_top) <- new_names
    genes_sel <- new_names
  }

  if (!is.null(gene_regulation)) {
    rownames(gene_regulation) <- genes_sel
  }

  # ---------------------------
  # 7) Apply z-score normalization
  # ---------------------------
  if (zscore) {
    mat_top <- t(scale(t(mat_top)))
  }

  # remove NA / Inf
  mat_top[!is.finite(mat_top)] <- 0

  # clamp extremes
  mat_top[mat_top > 2] <- 2
  mat_top[mat_top < -2] <- -2

  if (any(!is.finite(mat_top))) {
    warning("Non-finite values detected in heatmap matrix. Replaced with 0.")
  }

  # ---------------------------
  # 8) Prepare annotation
  # ---------------------------

  if (!group_col %in% colnames(metadata)) {
    stop(
      "Column '", group_col, "' not found in metadata.\n",
      "Available columns: ", paste(colnames(metadata), collapse = ", ")
    )
  }

  rownames(metadata) <- metadata$Sample

  ann_col <- data.frame(
    Group = factor(metadata[colnames(mat_top), group_col],
                   levels = unique(metadata[colnames(mat_top), group_col])),
    row.names = colnames(mat_top)
  )

  if (show_regulation && !is.null(res_df)) {
    annotation_row <- gene_regulation
    annotation_colors <- ann_colors
  } else {
    annotation_row <- NULL
    annotation_colors <- NULL
  }

  selection_method <- if (!is.null(contrast)) {
    "comparison"
  } else if (use_variance) {
    "variance"
  } else {
    "manual"
  }

  # --- Check gene number ---
  if (nrow(mat_top) < 2 && cluster_rows) {
    warning("Less than 2 genes selected. Row clustering disabled.")
    cluster_rows <- FALSE
  }

  if (ncol(mat_top) < 2 && cluster_cols) {
    warning("Less than 2 samples available. Column clustering disabled.")
    cluster_cols <- FALSE
  }


  # ---------------------------
  # 9) Plot heatmap
  # ---------------------------
  palette = grDevices::colorRampPalette(c("#3B4CC0", "white", "#d7191c"))(100)


  pheatmap::pheatmap(
    mat_top,
    cluster_rows = cluster_rows,
    cluster_cols = cluster_cols,
    show_rownames = show_rownames,
    show_colnames = show_colnames,
    annotation_col = ann_col,
    annotation_row = annotation_row,
    annotation_colors = annotation_colors,
    annotation_names_col = FALSE,
    annotation_names_row = FALSE,
    color = palette,
    border_color = NA,
    angle_col = 45,
    main = if (!is.null(contrast)) {
      sprintf("Top %d DEGs", length(genes_sel))
    } else {
      "Gene Expression Heatmap"
    }
  )

  # ---------------------------
  # 10) RNG handling
  # ---------------------------

  rng_state <- if (exists(".Random.seed", envir = .GlobalEnv)) .Random.seed else NULL

  seed <- if (is.null(seed)) {
    "not set"
  } else {
    as.character(seed)
  }

  # ---------------------------
  # 11) Return object
  # ---------------------------
  params <- list(
    timestamp = Sys.time(),
    group_col = group_col,
    top_n = top_n,
    use_variance = use_variance,
    zscore = zscore,
    cluster_rows = cluster_rows,
    cluster_cols = cluster_cols,
    dist_method = "euclidean",
    clustering_method = "complete",
    selection_method = selection_method,
    seed = seed,
    rng_state = rng_state
  )

  obj <- list(
    genes_used = genes_sel,
    heatmap_matrix = mat_top,
    annotation_col = ann_col,
    contrast = contrast,
    params = params
  )

  class(obj) <- "heatmap_result"

  # ---------------------------
  # 11) Attach to project
  # ---------------------------
  if (save) {

    proj <- .attach_to_project(
      proj,
      obj,
      slot = "analyses",
      subtype = "heatmap",
      prefix = "heatmap",
      log = list(
        method = selection_method,
        n = length(genes_sel),
        group = group_col,
        source = if (!is.null(contrast)) contrast else "none",
        seed = seed
      )
    )

  }

  print(obj)
  return(invisible(proj))
}

# ---------------------------
# 12) Print S3
# ---------------------------

#' Print method for GO objects
#' @name heatmap_result
#' @docType class
NULL

#' @method print heatmap_result
#' @export

print.heatmap_result <- function(x, ...) {

  .print_header("Heatmap Result")

  .print_block("Heatmap info", function() {
    cat("Genes used: ", length(x$genes_used), "\n", sep = "")
    cat("Z-score: ", x$params$zscore, "\n", sep = "")
    cat("Top n genes: ", x$params$top_n, "\n", sep = "")
    cat("Cluster rows: ", x$params$cluster_rows, "\n", sep = "")
    cat("Cluster cols: ", x$params$cluster_cols, "\n", sep = "")
    cat("Seed: ", x$params$seed, "\n", sep = "")
  })

  .print_block("Top 5 genes", function(){
    print(utils::head(x$genes_used, n = 5))
  })

  invisible(x)
}
